# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccpulse" do
  version "0.13.0"

  on_macos do
    on_arm do
      sha256 "6aeaa3bc8634f55cf89ff4d0b3b7ac4bca0318a2efd5822340eeb0106d55e582"
      url "https://github.com/martinciu/ccpulse/releases/download/v#{version}/ccpulse_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "23d544d75f791b5c191b1541e8354dc571768e8338891543638e1f94d78645f0"
      url "https://github.com/martinciu/ccpulse/releases/download/v#{version}/ccpulse_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "163c581ae6906b12fccbcbf32cb8590b866fd0e81b6f675a2f68522de23ce439"
      url "https://github.com/martinciu/ccpulse/releases/download/v#{version}/ccpulse_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "982e0858a40754d28fb5b855558dd95a428a79f92d404349a4ccd15195c48dc5"
      url "https://github.com/martinciu/ccpulse/releases/download/v#{version}/ccpulse_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ccpulse"
  desc "Native Go TUI dashboard for Claude Code usage"
  homepage "https://github.com/martinciu/ccpulse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccpulse"
  bash_completion "completions/ccpulse.bash"
  fish_completion "completions/ccpulse.fish"
  zsh_completion "completions/_ccpulse"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccpulse"]
    end
  end

  # No zap stanza required
end
