# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccpulse" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "a926f631e30689d24305da64ba6be85d2a41c2293e229be6763f028050e88692"
      url "https://github.com/martinciu/ccpulse/releases/download/v#{version}/ccpulse_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "69f2ec6ac3590e64b21d6204d538d0bbd386aaf0f6796842cc3cbb1953348d53"
      url "https://github.com/martinciu/ccpulse/releases/download/v#{version}/ccpulse_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a787ba9891ee06fc6f8a67c423e5042cf7f8fd4939eb7d7f425a52dd16d31e9f"
      url "https://github.com/martinciu/ccpulse/releases/download/v#{version}/ccpulse_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "327eb0fd6d83533462145196d1420afcf4ce32ca7b8b5ebbe4fd43ec96b9da6c"
      url "https://github.com/martinciu/ccpulse/releases/download/v#{version}/ccpulse_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ccpulse"
  desc "Native Go TUI dashboard for Claude Code usage"
  homepage "https://github.com/martinciu/ccpulse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccpulse"
  bash_completion "completions/ccpulse.bash"
  fish_completion "completions/ccpulse.fish"
  zsh_completion "completions/_ccpulse"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccpulse"]
    end
  end

  # No zap stanza required

end
