# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccpulse" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "26b97450af6ab1a85c524c3c7e3556da474c842ae55e7f68abe2e882e39b77bd"
      url "https://github.com/martinciu/ccpulse/releases/download/v#{version}/ccpulse_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a0346ea7fe59ce11be33c148c64ff5459835d753be4416977c85fc72667dba87"
      url "https://github.com/martinciu/ccpulse/releases/download/v#{version}/ccpulse_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "551781e9e068cb893cd9d84295e9da73bf28094be08ad53dfe932c094c25f6e7"
      url "https://github.com/martinciu/ccpulse/releases/download/v#{version}/ccpulse_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b34888789f034f7b17c125d6f3e3ff9c8908b3f00f4de93af82e09c1e7c312be"
      url "https://github.com/martinciu/ccpulse/releases/download/v#{version}/ccpulse_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ccpulse"
  desc "Native Go TUI dashboard for Claude Code usage"
  homepage "https://github.com/martinciu/ccpulse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccpulse"
  bash_completion "completions/ccpulse.bash"
  fish_completion "completions/ccpulse.fish"
  zsh_completion "completions/_ccpulse"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccpulse"]
    end
  end

  # No zap stanza required

end
